// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/status/v1beta1/uptime.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetUptimeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUptimeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUptimeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUptimeRequestMultiError, or nil if none found.
func (m *GetUptimeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUptimeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUptimeRequestMultiError(errors)
	}

	return nil
}

// GetUptimeRequestMultiError is an error wrapping multiple validation errors
// returned by GetUptimeRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUptimeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUptimeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUptimeRequestMultiError) AllErrors() []error { return m }

// GetUptimeRequestValidationError is the validation error returned by
// GetUptimeRequest.Validate if the designated constraints aren't met.
type GetUptimeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUptimeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUptimeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUptimeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUptimeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUptimeRequestValidationError) ErrorName() string { return "GetUptimeRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetUptimeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUptimeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUptimeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUptimeRequestValidationError{}

// Validate checks the field values on GetUptimeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUptimeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUptimeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUptimeResponseMultiError, or nil if none found.
func (m *GetUptimeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUptimeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uptime

	if all {
		switch v := interface{}(m.GetStarted()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUptimeResponseValidationError{
					field:  "Started",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUptimeResponseValidationError{
					field:  "Started",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStarted()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUptimeResponseValidationError{
				field:  "Started",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUptimeResponseMultiError(errors)
	}

	return nil
}

// GetUptimeResponseMultiError is an error wrapping multiple validation errors
// returned by GetUptimeResponse.ValidateAll() if the designated constraints
// aren't met.
type GetUptimeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUptimeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUptimeResponseMultiError) AllErrors() []error { return m }

// GetUptimeResponseValidationError is the validation error returned by
// GetUptimeResponse.Validate if the designated constraints aren't met.
type GetUptimeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUptimeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUptimeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUptimeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUptimeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUptimeResponseValidationError) ErrorName() string {
	return "GetUptimeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUptimeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUptimeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUptimeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUptimeResponseValidationError{}
